CREATE TABLE "pending_object_deletions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pending_object_deletions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"object_key" text NOT NULL,
	"reason" text NOT NULL,
	"purge_after" timestamp with time zone NOT NULL,
	"purged_at" timestamp with time zone,
	"last_error" text,
	"attempts" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "songs" ADD COLUMN "position" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
-- Backfill added by hand: the DEFAULT 0 above would tie every existing row,
-- and while (position, id) ordering keeps the list looking identical, the
-- first reorder would then be rewriting positions that never meant anything.
UPDATE "songs" SET "position" = "id";--> statement-breakpoint
CREATE INDEX "pending_object_deletions_purge_after_idx" ON "pending_object_deletions" USING btree ("purged_at","purge_after");--> statement-breakpoint
CREATE INDEX "songs_position_idx" ON "songs" USING btree ("position","id");